"""Add test_module to measurement and result

Revision ID: 21b079bd0acc
Revises: ef09260d3cb5
Create Date: 2026-08-26 18:29:18.814543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b079bd0acc'
down_revision: Union[str, Sequence[str], None] = 'ef09260d3cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('test_module', sa.String(), server_default='Accuracy', nullable=False))
    op.add_column('test_results', sa.Column('test_module', sa.String(), server_default='Accuracy', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'test_module')
    op.drop_column('measurements', 'test_module')
    # ### end Alembic commands ###
