"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { getHistoricalTestDetails, getTestAIExplanation, API_URL } from "@/lib/api";
import { CheckCircle2, XCircle, FileText, ChevronRight, Scale, AlertTriangle, ScrollText, Sparkles } from "lucide-react";

function AIExplanationBlock({ testId }: { testId: number }) {
    const [explanation, setExplanation] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    const fetchExplanation = async () => {
        setLoading(true);
        setError("");
        try {
            const res = await getTestAIExplanation(testId);
            if (res.status === "unavailable") {
                setError("AI explanation is currently unavailable (no API keys configured). The application will continue working normally with deterministic logic.");
            } else {
                setExplanation(res.explanation);
            }
        } catch (err: any) {
            setError(err.message || "Failed to fetch AI explanation.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="bg-gradient-to-r from-indigo-50 to-blue-50 border border-indigo-100 rounded-xl p-5 shadow-sm">
            <div className="flex items-center justify-between mb-3">
                <h3 className="font-bold text-indigo-900 flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-indigo-500" />
                    AI-Assisted Explanation
                </h3>
                {!explanation && !loading && (
                    <button 
                        onClick={fetchExplanation}
                        className="bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold px-3 py-1.5 rounded-lg transition-colors shadow-sm"
                    >
                        Explain Test Result
                    </button>
                )}
            </div>
            
            {loading && <p className="text-sm text-indigo-600 animate-pulse">Generating deterministic plain-language summary...</p>}
            {error && <p className="text-sm text-rose-600 font-medium bg-rose-50 p-2 rounded">{error}</p>}
            
            {explanation && (
                <div className="bg-white/80 p-4 rounded-lg text-sm text-slate-800 leading-relaxed border border-indigo-100 shadow-sm relative">
                    {explanation}
                    <div className="mt-3 pt-3 border-t border-indigo-100 text-xs text-indigo-500 font-medium flex justify-between items-center">
                        <span>Generated by MetraSure AI Assistant</span>
                        <span className="bg-indigo-100 px-2 py-0.5 rounded text-indigo-700">Does not override official rule engine</span>
                    </div>
                </div>
            )}
        </div>
    );
}
import { format } from "date-fns";

export default function HistoricalTestDetail() {
    const { id } = useParams();
    const testId = Number(id);
    
    const [data, setData] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");
    
    useEffect(() => {
        (async () => {
            try {
                const res = await getHistoricalTestDetails(testId);
                setData(res);
            } catch (err: any) {
                setError(err.message);
            } finally {
                setLoading(false);
            }
        })();
    }, [testId]);

    if (loading) return <div className="p-8 text-center text-slate-500 font-medium">Loading compliance audit...</div>;
    if (error) return <div className="p-4 bg-red-50 text-red-700 m-6 rounded-lg font-medium">{error}</div>;
    if (!data) return null;

    const { test, details } = data;

    // Group details by module
    const modules = details.reduce((acc: any, curr: any) => {
        if (!acc[curr.test_module]) acc[curr.test_module] = [];
        acc[curr.test_module].push(curr);
        return acc;
    }, {});

    return (
        <div className="max-w-5xl mx-auto space-y-6">
            <div className="flex items-center gap-2 text-sm text-slate-500 mb-2">
                <a href="/instruments" className="hover:text-blue-600 font-medium">Registry</a>
                <ChevronRight className="w-4 h-4" />
                <a href={`/instruments/${test.instrument_id}/history`} className="hover:text-blue-600 font-medium">Instrument Lifecycle</a>
                <ChevronRight className="w-4 h-4" />
                <span className="text-slate-800 font-bold">Audit Detail</span>
            </div>

            <div className="flex justify-between items-start">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Compliance Audit Trail</h1>
                    <p className="text-sm text-slate-500 font-mono mt-1">Ref: {test.test_number}</p>
                </div>
                <div className="flex items-center gap-4">
                    <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-bold border ${test.overall_result === 'PASS' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : test.overall_result === 'FAIL' ? 'bg-rose-50 text-rose-700 border-rose-200' : 'bg-amber-50 text-amber-700 border-amber-200'}`}>
                        {test.overall_result === "PASS" ? <CheckCircle2 className="w-4 h-4"/> : test.overall_result === "FAIL" ? <XCircle className="w-4 h-4"/> : <AlertTriangle className="w-4 h-4"/>} 
                        OVERALL {test.overall_result}
                    </span>
                </div>
            </div>

            <AIExplanationBlock testId={testId} />

            {Object.keys(modules).map(modName => (
                <div key={modName} className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden mb-6">
                    <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex items-center justify-between">
                        <h2 className="font-bold text-slate-800 flex items-center gap-2">
                            <ScrollText className="w-5 h-5 text-indigo-500" />
                            {modName} Test Module
                        </h2>
                    </div>
                    
                    <div className="overflow-x-auto">
                        <table className="min-w-full text-sm">
                            <thead className="bg-white text-slate-500 border-b border-slate-100 font-semibold">
                                <tr>
                                    <th className="px-6 py-3 text-left">Measurement Info</th>
                                    <th className="px-6 py-3 text-left">Calculation Engine</th>
                                    <th className="px-6 py-3 text-left">OIML Rule Applied</th>
                                    <th className="px-6 py-3 text-right">Result</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100">
                                {modules[modName].map((row: any, idx: number) => (
                                    <tr key={idx} className="hover:bg-slate-50 transition-colors">
                                        <td className="px-6 py-4">
                                            {row.measurement ? (
                                                <div className="space-y-1">
                                                    <p className="text-slate-900"><span className="text-slate-500">Load:</span> <span className="font-mono font-medium">{row.measurement.test_load}</span></p>
                                                    <p className="text-slate-900"><span className="text-slate-500">Indication:</span> <span className="font-mono font-medium">{row.measurement.indicated_value}</span></p>
                                                    {row.measurement.position && <p className="text-slate-900"><span className="text-slate-500">Pos:</span> {row.measurement.position}</p>}
                                                </div>
                                            ) : (
                                                <span className="text-slate-400 italic">Module-wide evaluation</span>
                                            )}
                                        </td>
                                        <td className="px-6 py-4 font-mono text-slate-800 space-y-1">
                                            <p className="text-xs text-slate-500 mb-1 font-sans">Determinism Trace</p>
                                            <p>Error: <span className="font-bold">{row.calculations.calculated_error}</span></p>
                                            <p>Limit: ±{row.calculations.permissible_error}</p>
                                        </td>
                                        <td className="px-6 py-4">
                                            {row.rule_used ? (
                                                <div>
                                                    <p className="font-bold text-slate-800">{row.rule_used.rule_id}</p>
                                                    <p className="text-xs text-slate-500 mt-1">{row.rule_used.standard} ({row.rule_used.standard_version})</p>
                                                    <p className="text-xs text-slate-500 mt-0.5">Formula: {row.rule_used.formula_reference}</p>
                                                </div>
                                            ) : (
                                                <span className="text-slate-400">N/A</span>
                                            )}
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            {row.result === "PASS" ? (
                                                <span className="inline-flex items-center gap-1 px-2 py-1 bg-emerald-50 text-emerald-700 font-bold text-xs rounded border border-emerald-100"><CheckCircle2 className="w-3.5 h-3.5"/> PASS</span>
                                            ) : (
                                                <div className="flex flex-col items-end gap-1">
                                                    <span className="inline-flex items-center gap-1 px-2 py-1 bg-rose-50 text-rose-700 font-bold text-xs rounded border border-rose-100"><XCircle className="w-3.5 h-3.5"/> FAIL</span>
                                                    {row.explanation && (
                                                        <p className="text-xs text-rose-600 max-w-[200px] mt-1 text-right leading-tight bg-white border border-rose-200 p-1.5 rounded shadow-sm">{row.explanation}</p>
                                                    )}
                                                </div>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            ))}
        </div>
    );
}
